-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["block"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "block", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   63, -80  ,  150, 89  ,  -151, 89  ,  -150, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "block", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   150, -82  ,  150, 89  ,  63, -80  }
                    }
                                        
                    
                    
		}
		
		, 
		["house"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "house", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   38, -25.5  ,  36, 2.5  ,  -41, 1.5  ,  -41, -26.5  ,  -21, -56.5  ,  17, -56.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "house", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   64, 21.5  ,  62, 56.5  ,  -64, 56.5  ,  -64, 21.5  ,  -51.5, 2.5  ,  -41, 1.5  ,  36, 2.5  ,  50, 3.5  }
                    }
                    
                    
                    
		}
		
		, 
		["school"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "school", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   108, 30.5  ,  -108, 28.5  ,  -112, -69.5  ,  111, -69.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "school", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -108, 28.5  ,  108, 30.5  ,  119, 69.5  ,  -118, 69.5  ,  -121, 29.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "school", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   119, 69.5  ,  108, 30.5  ,  120, 29.5  }
                    }
                    
                    
                    
		}
		
		, 
		["tower"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -63.5, -38.5  ,  -49.5, -40.5  ,  50.5, -38.5  ,  58.5, 111.5  ,  -61.5, 111.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   50.5, -38.5  ,  31.5, -64.5  ,  50.5, -65.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -33.5, -64.5  ,  50.5, -38.5  ,  -49.5, -40.5  ,  -49.5, -65.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   19.5, -111.5  ,  21.5, -93.5  ,  -22.5, -92.5  ,  -21.5, -111.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -22.5, -92.5  ,  -33.5, -64.5  ,  -33.5, -92.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   29.5, -93.5  ,  31.5, -64.5  ,  -33.5, -64.5  ,  -22.5, -92.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   50.5, -38.5  ,  -33.5, -64.5  ,  31.5, -64.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "tower", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   58.5, 111.5  ,  50.5, -38.5  ,  62.5, -39.5  }
                    }
                    
                    
                    
		}
		
		, 
		["towers_inc"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -73.5, -7.5  ,  -50.5, -31.5  ,  -27.5, -32.5  ,  73.5, 129.5  ,  -72.5, 129.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   48.5, -129.5  ,  72.5, -98.5  ,  24.5, -91.5  ,  24.5, -129.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   24.5, -91.5  ,  -27.5, -32.5  ,  -27.5, -61.5  ,  -2.5, -92.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   72.5, -98.5  ,  73.5, 129.5  ,  -27.5, -32.5  ,  24.5, -91.5  }
                    }
                    
                    
                    
		}
		
		, 
		["barn"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "barn", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65495, groupIndex = 0 },
                    shape = {   -83.5, 81.5  ,  -87.5, 3.5  ,  -61.5, -45.5  ,  -40.5, 31.5  ,  -40.5, 81.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "barn", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65495, groupIndex = 0 },
                    shape = {   12.5, 31.5  ,  29.5, -42.5  ,  52.5, -2.5  ,  50.5, 81.5  ,  12.5, 81.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "barn", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65495, groupIndex = 0 },
                    shape = {   29.5, -42.5  ,  12.5, 31.5  ,  -40.5, 31.5  ,  -61.5, -45.5  ,  -23.5, -79.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "barn", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65495, groupIndex = 0 },
                    shape = {   54.5, -71.5  ,  88.5, -69.5  ,  88.5, 79.5  ,  52.5, 79.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "barn", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65495, groupIndex = 0 },
                    shape = {   88.5, -69.5  ,  54.5, -71.5  ,  73.5, -78.5  }
                    }
                    
                    
                    
		}
		
		, 
		["fence"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "fence", density = 1, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -28.5, 22.5  ,  -28.5, -17.5  ,  28.5, -17.5  ,  28.5, 22.5  }
                    }
                    
                    
                    
		}
		
		, 
		["towers_dec"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "towers_dec", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   1, -70.5  ,  -66, 124.5  ,  -30, -99.5  ,  0, -99.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "towers_dec", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   33, -42.5  ,  -66, 124.5  ,  1, -70.5  ,  33, -70.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "towers_dec", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -66, 124.5  ,  33, -42.5  ,  65, -42.5  ,  66, 124.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "towers_dec", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   -30, -99.5  ,  -66, 124.5  ,  -66, -124.5  ,  -30, -124.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ground"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "ground", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 23, groupIndex = 0 },
                    shape = {   240, -7  ,  240, 14  ,  -240, 14  ,  -240, -7  }
                    }
                    
                    
                    
		}
		
		, 
		["ufo12"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "ufo", density = 0.3, friction = 0.3, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 94, groupIndex = 0 },
                    shape = {   19.5, -12.5  ,  11.5, 21  ,  -10.5, 21  ,  -36.5, 11  ,  -17.5, -13.5  ,  -7.5, -22  ,  8.5, -22  }
                    }
                     ,
                    {
                    pe_fixture_id = "ufo", density = 0.3, friction = 0.3, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 94, groupIndex = 0 },
                    shape = {   -47.5, -1  ,  -17.5, -13.5  ,  -36.5, 11  ,  -47.5, 3  }
                    }
                     ,
                    {
                    pe_fixture_id = "ufo", density = 0.3, friction = 0.3, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 94, groupIndex = 0 },
                    shape = {   47.5, -1  ,  47.5, 3  ,  34.5, 12  ,  11.5, 21  ,  19.5, -12.5  }
                    }
                    
                     ,
					 
					 
                    
		}
		
		,
		["scarecrow"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "scarecrow", density = 2, friction = 0.4, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   6, -41.5  ,  6, -27.5  ,  -7, -27.5  ,  -7, -41.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "scarecrow", density = 2, friction = 0.4, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   8, -18.5  ,  -7, -18.5  ,  -29, -23.5  ,   29, -23.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "scarecrow", density = 2, friction = 0.4, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 23, groupIndex = 0 },
                    shape = {   8, -18.5  ,  7, 42.5  ,  -6, 42.5  ,  -7, -18.5  }
                    }
                    
                    
                    
		}
		
		, 
		["beam"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "beam", density = 0, friction = 0, bounce = 0, isSensor=true, 
                    filter = { categoryBits = 32, maskBits = 68, groupIndex = 0 },
                    shape = {   -15.5, -111  ,  15.5, -111  ,  23.5, 0  ,  -23.5, 0  }
                    }
                    
                    
                    
		}
		
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

